CREATE TABLE IF NOT EXISTS users
(
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(128)                            NOT NULL,
    email   VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (user_id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS requests
(
    request_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description  VARCHAR(512)                            NOT NULL,
    requester_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_requests PRIMARY KEY (request_id),
    FOREIGN KEY (requester_id)
        REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS items
(
    item_id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(128)                            NOT NULL,
    description  VARCHAR(512)                            NOT NULL,
    is_available BOOLEAN DEFAULT FALSE,
    user_id      BIGINT                                  NOT NULL,
    request_id   BIGINT                                  ,
    CONSTRAINT pk_items PRIMARY KEY (item_id),
    FOREIGN KEY (user_id)
        REFERENCES users (user_id) ON DELETE CASCADE,
    FOREIGN KEY (request_id)
        REFERENCES requests (request_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS bookings
(
    booking_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_date TIMESTAMP WITH TIME ZONE                NOT NULL,
    end_date   TIMESTAMP WITH TIME ZONE                NOT NULL,
    item_id    BIGINT                                  NOT NULL,
    booker_id  BIGINT                                  NOT NULL,
    status     VARCHAR(20),
    CONSTRAINT pk_bookings PRIMARY KEY (booking_id),
    FOREIGN KEY (item_id)
        REFERENCES items (item_id) ON DELETE CASCADE,
    FOREIGN KEY (booker_id)
        REFERENCES users (user_id) ON DELETE CASCADE
);

